# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.workflow }}-
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Install dependencies
      run: mvn dependency:go-offline compile compiler:testCompile
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Run tests and generate Allure report
      run: mvn clean test
      if: always()
      env:
        ALLURE_RESULTS_FOLDER: target/allure-results
      # Generate screenshot on test failure
      - name: Generate screenshot on test failure
        if: failure()
        run: |
          mkdir -p target/screenshots/
          mvn io.github.bonigarcia:webdrivermanager-maven-plugin:latest:binaries -DoutputDirectory=$HOME/.m2/repository/webdriver
          mvn com.github.webdriverextensions:webdriverextensions-maven-plugin:2.1.1:capture-screenshot -Dscreenshot.directory=target/screenshots/
      # Attach screenshot to Allure report
      - name: Attach screenshot to Allure report
        if: failure()
        run: |
          mkdir -p target/allure-results
          for file in target/screenshots/*.png; do allure generate $file --output target/allure-results --clean; done
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
